### ISSUE TITLE
config.log() documentation

### ISSUE THREAD

**Issue by theofidry** [tridium/niagara-station#2]
Case of the second parameter (`level`)

Current doc: `Log level, e.g. WARNING or INFO. Will be undefined if no log level specified.`

The default value is not specified (I assume `'INFO'`?). The doc should be changed or maybe a better way would be to follow [JSDoc recommendations](http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values) and change the signature `config.log(string msg, string [level], string [pkg])` to `config.log(string msg, string [level='INFO'], string [pkg='?Value to be placed here?'])`.

Same comment for the last parameter (`pkg`). Still, thanks for merging the `config.log` and `config.err` ;)

**Comment by tridium** [comment]
`config.log` is a callback function that handles data coming back from the station. This is a function for the user to implement themselves if needed. The `level` and `pkg` parameters are dependent on what the station itself is logging, so it doesn't make sense to make a default value for them.

**Comment by theofidry** [comment]
Then maybe it should be precise in the doc of the function, something along the lines `optional callback function for logging console info from station.`?

**Comment by tridium** [comment]
Added an example and changed the wording.
